### ISSUE TITLE
how to only let 127.0.0.1 access this socks5?

### ISSUE THREAD

**Issue by luckypoem** [glftpd/socks5#2]
hi.

[root@host socks5-by-glftpd]# netstat -tulpn|grep socks5
tcp        0      0 0.0.0.0:123             0.0.0.0:*               LISTEN      5610/./bin/socks5   
[root@host socks5-by-glftpd]#

tks

**Comment by hrxcodes** [comment]
[listen_ip](https://github.com/glftpd/socks5/blob/master/socks5.conf.dist#L9) should do I think

**Comment by hrxcodes** [comment]
@luckypoem did you have any success with that?

**Comment by luckypoem** [comment]
yes.thank u

**Comment by hrxcodes** [comment]
> yes.thank u

Great, please close the issue.
Thanks
