### ISSUE TITLE
"error resolving ip: somename.dyndns.org" (plain IP works fine)

### ISSUE THREAD

**Issue by Stiefmeister** [glftpd/socks5#4]
Hi,

first of all thanks for this neat piece of software.

Got a problem when connecting to dns-name (e.g. somename.dyndns.org).
Socks5 debug gives me: "error resolving ip: somename.dyndns.org"

When connecting to IP it works flawlessly.
nslookup somename.dyndns.org works, so does not seem to be a server issue!?

Thanks a lot in advance and stay healthy!

**Comment by glftpd** [comment]
can you change your config to enable debug log to file and see if you get any errors ?

**Comment by Stiefmeister** [comment]
Hi,

debug log just states: "error resolving ip: somename.dyndns.org"
No other error message. 

Any way else to test if my vserver config is maybe faulty? Using Ubuntu 16.04 btw.

**Comment by awknode** [comment]
don't run it as root.

**Comment by Stiefmeister** [comment]
> 
> 
> don't run it as root.

Worked, thanks!
